// REAL DTOs based on actual backend API responses
// Generated by analyzing live API responses from http://localhost:5000

export type UserRole = 'CLIENT' | 'ADMIN' | 'AGENT' | 'EXPERT';

// ========================================
// USER & AUTH
// ========================================
export interface UserDTO {
  _id: string;
  id?: string; // Alias for _id from backend
  email: string;
  name: string;
  telephone?: string;
  role: UserRole;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  token: string;
  user: UserDTO;
}

export interface RegisterRequest {
  name: string;
  email: string;
  password: string;
  telephone?: string;
  role?: UserRole;
}

// ========================================
// VEHICLE
// ========================================
export type VehicleUsage = 'PRIVATE' | 'COMMERCIAL' | 'TAXI';

export interface VehicleDTO {
  _id: string;
  userId: string;
  plateNumber: string;
  brand: string;
  model: string;
  year: number;
  marketValue: number;
  usage: VehicleUsage;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateVehicleRequest {
  plateNumber: string;
  brand: string;
  model: string;
  year: number;
  marketValue: number;
  usage: VehicleUsage;
}

export interface UpdateVehicleRequest {
  plateNumber?: string;
  brand?: string;
  model?: string;
  year?: number;
  marketValue?: number;
  usage?: VehicleUsage;
}

// ========================================
// PRODUCT (REAL STRUCTURE FROM BACKEND)
// ========================================
export interface ProductGuarantee {
  _id?: string;
  id?: string;
  code: string;
  label: string;
  required: boolean;
}

export interface ProductOption {
  _id?: string;
  id?: string;
  code: string;
  label: string;
  price: number;
}

export interface ProductDTO {
  _id: string;
  code: string;
  name: string;
  description: string;
  guarantees: ProductGuarantee[];
  options: ProductOption[];
  franchise: {
    amount: number;
    type: string; // 'FIXED' | 'PERCENTAGE'
  };
  pricing: {
    baseRate: number;
    vehicleValueRate: number;
  };
  eligibility: {
    minVehicleYear: number;
    maxVehicleYear: number;
    allowedCategories: string[]; // ['CAR', 'MOTORBIKE', 'TRUCK']
  };
  active?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

// ========================================
// QUOTE
// ========================================
export type QuoteStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED' | 'ACCEPTED';

export interface QuoteDTO {
  _id: string;
  userId: string;
  vehicleId: string;
  productCode: string;
  coverageOptions?: string[];
  requestedStartDate?: string;
  amount: number;
  status: QuoteStatus;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
  vehicle?: VehicleDTO;
  product?: ProductDTO;
}

export type ProductCode = 'TIERS' | 'TIERS_PLUS' | 'TOUS_RISQUES';
export type OptionCode = 'BRIS_GLACE' | 'ASSISTANCE' | 'VEHICULE_REMPLACEMENT' | 'PROTECTION_JURIDIQUE';

export interface CreateQuoteRequest {
  vehicleId: string;
  productCode: ProductCode;
  selectedOptionCodes?: OptionCode[];
}

// ========================================
// POLICY
// ========================================
export type PolicyStatus = 'ACTIVE' | 'EXPIRED' | 'CANCELLED' | 'PENDING';

export interface PolicyDTO {
  _id: string;
  userId: string;
  quoteId: string;
  vehicleId: string;
  productCode: string;
  startDate: string;
  endDate: string;
  amount: number;
  status: PolicyStatus;
  paymentMethod: string;
  paymentReference?: string;
  createdAt: string;
  updatedAt: string;
  quote?: QuoteDTO;
  vehicle?: VehicleDTO;
}

export type PaymentMethod = 'CARD' | 'BANK_TRANSFER' | 'CASH';

export interface CreatePolicyRequest {
  quoteId: string;
  startDate: string; // YYYY-MM-DD
  duration: number; // 6 or 12 months
  paymentMethod: PaymentMethod;
}

export interface RenewPolicyRequest {
  paymentMethod: string;
  paymentReference?: string;
}

export interface CancelPolicyRequest {
  reason: string;
}

// ========================================
// DOCUMENT (REAL STRUCTURE)
// ========================================
export type DocumentType = 'ATTESTATION' | 'CONTRACT' | 'RECEIPT' | 'CLAIM_ATTACHMENT' | 'OTHER';

export interface DocumentDTO {
  _id: string;
  entityType: string;
  entityId: string;
  type: DocumentType;
  filename: string;
  mimeType: string;
  size: number;
  path: string;
  url?: string;
  createdAt: string;
}

// ========================================
// CLAIM (REAL STRUCTURE)
// ========================================
export type ClaimStatus = 'PENDING' | 'UNDER_REVIEW' | 'APPROVED' | 'REJECTED' | 'SETTLED' | 'NEED_MORE_INFO';

export interface ClaimIncident {
  date: string;
  location: string;
  type: string;
  description: string;
}

export interface ClaimDTO {
  _id: string;
  userId: string;
  policyId: string;
  incident: ClaimIncident;
  status: ClaimStatus;
  estimatedAmount?: number;
  settledAmount?: number;
  createdAt: string;
  updatedAt: string;
  policy?: PolicyDTO & {
    policyNumber?: string;
  };
  owner?: {
    _id: string;
    name: string;
    firstName?: string;
    lastName?: string;
    email: string;
    phone?: string;
  };
  vehicle?: {
    _id: string;
    brand: string;
    model: string;
    year?: number;
    plateNumber?: string;
  };
  attachments?: Array<{
    url: string;
    name: string;
    mimetype?: string;
  }>;
  history?: Array<{
    action: string;
    by: string;
    timestamp: string;
    details?: string;
  }>;
  notes?: Array<{
    content: string;
    isInternal: boolean;
    createdAt: string;
    createdBy: {
      firstName: string;
      lastName: string;
    };
  }>;
  expert?: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
}

export interface CreateClaimRequest {
  policyId: string;
  incident: ClaimIncident;
}

export interface ClaimMessageRequest {
  message: string;
}

// ========================================
// NOTIFICATION (REAL STRUCTURE)
// ========================================
export type NotificationType = 'INFO' | 'WARNING' | 'SUCCESS' | 'ERROR';

export interface NotificationDTO {
  _id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
}

// ========================================
// DASHBOARD (REAL STRUCTURE FROM BACKEND)
// ========================================
export interface DashboardKPIs {
  policies: {
    total: number;
    active: number;
    expired: number;
    byStatus: Array<{
      status: string;
      count: number;
    }>;
  };
  claims: {
    total: number;
    settled: number;
    pending: number;
    byStatus: Array<{
      status: string;
      count: number;
    }>;
  };
  financials: {
    totalPremium: number;
    currency: string;
  };
  quotes: {
    total: number;
    accepted: number;
    conversionRate: number;
  };
  users: {
    total: number;
    active: number;
  };
  vehicles: {
    total: number;
  };
}

export interface DashboardTrend {
  year: number;
  month: number;
  count?: number;
  revenue?: number;
  amount?: number;
}

export interface DashboardTrends {
  policies: DashboardTrend[];
  claims: DashboardTrend[];
  revenue: DashboardTrend[];
}

export interface DashboardProductStats {
  _id: string;
  count: number;
  revenue: number;
  productId: string;
  productCode: string;
  productName: string;
}

export interface DashboardDocumentStats {
  type: string;
  count: number;
  totalSize: number;
}

export interface DashboardData {
  kpis: DashboardKPIs;
  trends: DashboardTrends;
  topProducts: DashboardProductStats[];
  documentStats: DashboardDocumentStats[];
}

// ========================================
// AUDIT LOG (REAL STRUCTURE)
// ========================================
export type AuditAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'VIEW' | 'LOGIN' | 'LOGOUT' | 'APPROVE' | 'REJECT';

export interface AuditLogDTO {
  _id: string;
  user: {
    id: string;
    email: string;
    role: string;
  };
  action: AuditAction;
  entity: {
    type: string; // 'User', 'Policy', 'Claim', etc.
    id: string;
  };
  changes?: {
    before?: Record<string, any>;
    after?: Record<string, any>;
  };
  metadata?: {
    ip?: string;
    userAgent?: string;
    [key: string]: any;
  };
  timestamp: string;
  createdAt: string;
}

export interface AuditLogStatsDTO {
  totalLogs: number;
  byAction: Record<string, number>;
  byEntity: Record<string, number>;
  byUser: Array<{
    userId: string;
    userEmail: string;
    count: number;
  }>;
}
